# NOT COMPLETE
FROM python:3.11-slim

WORKDIR /app

COPY ./backend/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./backend .

# Create data directories
RUN mkdir -p data/local_storage data/cloud_storage data/versions

# Add volume for persistent storage
VOLUME ["/app/data"]

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
